mysql:
  image: mysql
  ports:
    - "3306:3306" # <-これがないと外からアクセス出来ない
  expose:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
  volumes:
    - ".:/src"
